[package]
name = "solanahello"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
blake3 = "1.5.1"
solana-program = "2.0.1"

[lib]
name = "solanahello"
crate-type = ["cdylib", "lib"]